### PR TITLE
Graph module (source + tests)

### PR DESCRIPTION
**Pull request by SatyendraBanjare**
Added lua bindings and tests for graph module.

### CODE REVIEW

**Comment by Etiene** [comment]
Could you solve the conflicts from this and other open PRs? :)

**Comment by SatyendraBanjare** [comment]
Yes mam I will solve and merge them. (tomorrow :smile: )

**Comment by Etiene** [comment]
Don't merge things that arent approved yet, if it's not approved I haven't finished reviewing :)

**Comment by SatyendraBanjare** [comment]
ok, I will merge only after they are approved.

**Comment by SatyendraBanjare** [comment]
rebased for easy merge

**Review by Etiene — APPROVED** [review]
👍

**Pull request merged**
