### PR TITLE
Luagit2 for lua5.3

### PR DESCRIPTION
**Pull request by SatyendraBanjare**
The changes installs luagit2 by both the methods of `cmake/make` and `luarocks`. It is currently compatible for lua5.3 only. 

I have added few tests written using busted to try out luagit2.

### CODE REVIEW

**Comment by Etiene** [comment]
So far it looks alright when installing with luarocks.
When installing with cmake I get the following error when running the tests
```
./libgit/test_libgit_spec.lua:5: module 'luagit2' not found:No LuaRocks module found for luagit2
	no field package.preload['luagit2']
	no file './src/luagit2.lua'
	no file './src/luagit2/luagit2.lua'
	no file './src/luagit2/init.lua'
	no file '/Users/etiene/.luarocks/share/lua/5.3/luagit2.lua'
	no file '/Users/etiene/.luarocks/share/lua/5.3/luagit2/init.lua'
	no file '/usr/local/share/lua/5.3/luagit2.lua'
	no file '/usr/local/share/lua/5.3/luagit2/init.lua'
	no file '/usr/local/lib/lua/5.3/luagit2.lua'
	no file '/usr/local/lib/lua/5.3/luagit2/init.lua'
	no file './luagit2.lua'
	no file './luagit2/init.lua'
	no file './csrc/luagit2.so'
	no file './csrc/luagit2/luagit2.so'
	no file '/Users/etiene/.luarocks/lib/lua/5.3/luagit2.so'
	no file '/usr/local/lib/lua/5.3/luagit2.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './luagit2.so'
```

**Comment by Etiene** [comment]
Can you change the base of the of this PR to `Separated_definitions_declarations` instead of master?  There are commits showing here that do not belong to this PR :)

**Comment by SatyendraBanjare** [comment]
I have changed the base branch :smile:

**Review by Etiene — APPROVED** [review]
🎉

**Pull request merged**
