### PR TITLE
Travis : Added Initial Test Setup (only for linux dist : Xenial)

### PR DESCRIPTION
**Pull request by SatyendraBanjare**
I have added a simple travis setup for luagit2. It successfully installs luagit2 using both `cmake/ make`, `luarocks`.

The build status can be seen here : https://www.travis-ci.org/SatyendraBanjare/luagit2/builds/413816886

### CODE REVIEW

**Comment by Etiene** [comment]
I notice that on line 1704 of the output of this build 
https://www.travis-ci.org/SatyendraBanjare/luagit2/builds/413931096
there was a failure in a test
`Failure → commit/test_commit_spec.lua @ 126`
but the build was still successful, it shouldn't! 

To fix this you might have to modify test-all.sh to exit with an error if busted fails.
But actually you might not even need the test-all script but just run busted directly instead with the correct flags and parameters.

**Comment by Etiene** [comment]
Another thing I would like to add as a suggestion is a moving back the .git/.gitted folders and other modifications to its initial state in case a test fails.

**Comment by Etiene** [comment]
Excellent work on getting CI btw!

**Comment by SatyendraBanjare** [comment]
Thankyou so much :smile:

**Comment by SatyendraBanjare** [comment]
>Another thing I would like to add as a suggestion is a moving back the .git/.gitted folders and other modifications to its initial state in case a test fails. 

Yes I will try to do it. Thankyou.

**Pull request merged**
